insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (1, 'Persahabatan', 17, 'KLINIK', 74);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (2, 'Manuela', 13, 'RUMAH SAKIT', 63);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (3, 'Fatmawati', 9, 'PUSKESMAS', 87);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (4, 'MMC', 33, 'KLINIK', 82);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (5, 'Evasari', 26, 'KLINIK', 91);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (6, 'Sukmul', 47, 'KLINIK', 61);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (7, 'Koja', 11, 'PUSKESMAS', 2);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (8, 'Cengkareng', 0, 'KLINIK', 83);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (9, 'Pusdikkes', 118, 'RUMAH SAKIT', 83);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (10, 'Hermina', 28, 'RUMAH SAKIT', 31);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (11, 'Yadika', 29, 'RUMAH SAKIT', 81);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (12, 'Tarakan', 45, 'RUMAH SAKIT', 86);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (13, 'Family', 34, 'PUSKESMAS', 85);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (14, 'Mulyasari', 47, 'PUSKESMAS', 46);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (15, 'Amlapura', 17, 'PUSKESMAS', 41);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (16, 'Wangaya', 45, 'KLINIK', 42);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (17, 'Negara', 44, 'KLINIK', 8);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (18, 'Badung', 29, 'KLINIK', 57);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (19, 'Tabanan', 11, 'KLINIK', 52);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (20, 'Premagana', 13, 'KLINIK', 7);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (21, 'Klungkung', 48, 'PUSKESMAS', 5);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (22, 'Bangli', 75, 'RUMAH SAKIT', 10);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (23, 'Brebes', 19, 'PUSKESMAS', 18);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (24, 'SELARAS', 15, 'PUSKESMAS', 71);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (25, 'Tiara', 40, 'KLINIK', 3);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (26, 'Mayapada', 34, 'PUSKESMAS', 73);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (27, 'Tidar', 28, 'PUSKESMAS', 79);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (28, 'Roemani', 26, 'PUSKESMAS', 58);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (29, 'Dr.Oen', 27, 'KLINIK', 22);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (30, 'Kotabaru', 119, 'RUMAH SAKIT', 66);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (31, 'Banjarbaru', 30, 'KLINIK', 25);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (32, 'Kab.Sekadau', 81, 'RUMAH SAKIT', 37);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (33, 'Melawi', 23, 'PUSKESMAS', 77);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (34, 'St.Antonius', 151, 'RUMAH SAKIT', 44);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (35, 'Sambas', 17, 'RUMAH SAKIT', 4);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (36, 'Liwa', 6, 'PUSKESMAS', 49);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (37, 'Pringsewu', 24, 'KLINIK', 49);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (38, 'Sukadana', 8, 'RUMAH SAKIT', 61);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (39, 'Dabo', 22, 'PUSKESMAS', 42);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (40, 'Natuna', 12, 'KLINIK', 99);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (41, 'Kalianda', 41, 'RUMAH SAKIT', 16);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (42, 'Kolaka', 11, 'PUSKESMAS', 27);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (43, 'Bombana', 71, 'RUMAH SAKIT', 99);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (44, 'Wakatobi', 29, 'KLINIK', 19);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (45, 'Namrole', 143, 'RUMAH SAKIT', 6);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (46, 'Raha', 35, 'KLINIK', 35);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (47, 'Unaaha', 187, 'RUMAH SAKIT', 92);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (48, 'Noongan', 44, 'PUSKESMAS', 101);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (49, 'Morowali', 21, 'PUSKESMAS', 11);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (50, 'Ampana', 41, 'PUSKESMAS', 35);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (51, 'Kabelota', 17, 'KLINIK', 25);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (52, 'Buol', 8, 'KLINIK', 84);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (53, 'Tangerang', 20, 'KLINIK', 69);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (54, 'Budiasih', 28, 'PUSKESMAS', 86);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (55, 'Melati', 4, 'PUSKESMAS', 34);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (56, 'Kurnia', 17, 'PUSKESMAS', 76);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (57, 'Malingping', 189, 'RUMAH SAKIT', 85);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (58, 'Rafflesia', 17, 'PUSKESMAS', 2);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (59, 'Curup', 134, 'RUMAH SAKIT', 48);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (60, 'Mukomuko', 42, 'PUSKESMAS', 32);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (61, 'Manna', 21, 'KLINIK', 82);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (62, 'Muaradua', 47, 'PUSKESMAS', 66);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (63, 'Kepahiang', 84, 'RUMAH SAKIT', 13);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (64, 'Wates', 55, 'RUMAH SAKIT', 37);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (65, 'Prambanan', 170, 'RUMAH SAKIT', 61);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (66, 'Wonosari', 17, 'PUSKESMAS', 55);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (67, 'Sleman', 6, 'KLINIK', 77);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (68, 'Tombulilato', 148, 'RUMAH SAKIT', 16);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (69, 'Pohuwato', 45, 'KLINIK', 40);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (70, 'Karawang', 84, 'RUMAH SAKIT', 6);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (71, 'Meilia', 156, 'RUMAH SAKIT', 68);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (72, 'Cianjur', 127, 'RUMAH SAKIT', 56);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (73, 'Pandeglang', 11, 'RUMAH SAKIT', 55);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (74, 'Ciawi', 5, 'PUSKESMAS', 11);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (75, 'Indramayu', 21, 'PUSKESMAS', 72);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (76, 'Cibinong', 73, 'RUMAH SAKIT', 97);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (77, 'Waled', 183, 'RUMAH SAKIT', 1);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (78, 'Bekasi', 20, 'PUSKESMAS', 86);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (79, 'Kebonjati', 25, 'PUSKESMAS', 49);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (80, 'Sekarwangi', 114, 'RUMAH SAKIT', 79);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (81, 'Cimacan', 91, 'RUMAH SAKIT', 10);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (82, 'Majalaya', 23, 'PUSKESMAS', 94);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (83, 'Cibabat', 4, 'PUSKESMAS', 50);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (84, 'Soreang', 184, 'RUMAH SAKIT', 47);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (85, 'Tasikmalaya', 25, 'KLINIK', 24);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (86, 'Ciamis', 32, 'PUSKESMAS', 55);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (87, 'Banjar', 3, 'KLINIK', 29);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (88, 'Kuningan', 48, 'KLINIK', 29);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (89, 'Sidawangi', 114, 'RUMAH SAKIT', 81);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (90, 'Arjawinangun', 101, 'RUMAH SAKIT', 6);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (91, 'Majalengka', 12, 'KLINIK', 29);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (92, 'Cideres', 105, 'RUMAH SAKIT', 99);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (93, 'Sumedang', 9, 'KLINIK', 11);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (94, 'Subang', 37, 'PUSKESMAS', 5);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (95, 'Medika', 118, 'RUMAH SAKIT', 41);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (96, 'Ananda', 15, 'PUSKESMAS', 44);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (97, 'Kab.Bekasi', 18, 'PUSKESMAS', 49);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (98, 'Sragen', 71, 'RUMAH SAKIT', 70);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (99, 'Majenang', 78, 'RUMAH SAKIT', 34);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (100, 'Banjarnegara', 24, 'KLINIK', 66);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (101, 'Banyudono', 26, 'KLINIK', 76);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (102, 'Pekalongan', 21, 'PUSKESMAS', 13);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (103, 'Cilacap', 2, 'KLINIK', 44);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (104, 'Wonosobo', 31, 'PUSKESMAS', 64);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (105, 'Amanah', 13, 'PUSKESMAS', 58);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (106, 'Banyumas', 43, 'PUSKESMAS', 71);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (107, 'Ajibarang', 27, 'KLINIK', 1);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (108, 'Purbalinnga', 36, 'PUSKESMAS', 56);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (109, 'Nirmala', 21, 'KLINIK', 78);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (110, 'Kebumen', 43, 'PUSKESMAS', 94);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (111, 'Simo', 6, 'RUMAH SAKIT', 79);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (112, 'Sujoharjo', 74, 'RUMAH SAKIT', 97);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (113, 'Karanganyar', 172, 'RUMAH SAKIT', 27);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (114, 'Assalam', 30, 'KLINIK', 36);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (115, 'Blora', 9, 'KLINIK', 11);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (116, 'Pati', 30, 'PUSKESMAS', 10);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (117, 'Kudus', 50, 'KLINIK', 83);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (118, 'Kudus', 45, 'KLINIK', 19);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (119, 'Ambarawa', 34, 'KLINIK', 19);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (120, 'Ungaran', 5, 'PUSKESMAS', 26);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (121, 'Kardinah', 14, 'KLINIK', 18);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (122, '&quot;Kanjuruhan&quot;Kepanjen', 33, 'PUSKESMAS', 49);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (123, 'Lawang', 38, 'KLINIK', 55);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (124, 'Genteng', 12, 'KLINIK', 3);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (125, 'Sumberrejo', 128, 'RUMAH SAKIT', 32);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (126, 'Al-irsyad', 32, 'KLINIK', 5);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (127, 'PHC', 162, 'RUMAH SAKIT', 13);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (128, 'An-Nisaa', 21, 'RUMAH SAKIT', 11);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (129, 'Blambangan', 113, 'RUMAH SAKIT', 71);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (130, 'Pare', 38, 'PUSKESMAS', 78);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (131, 'Jember', 3, 'PUSKESMAS', 47);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (132, 'Balung', 36, 'KLINIK', 15);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (133, 'Bangil', 47, 'KLINIK', 66);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (134, 'Sidoarjo', 3, 'PUSKESMAS', 34);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (135, 'Muslimat', 1, 'PUSKESMAS', 20);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (136, 'Nganjuk', 19, 'PUSKESMAS', 16);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (137, 'Kertosono', 21, 'KLINIK', 49);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (138, 'Dungus', 49, 'PUSKESMAS', 12);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (139, 'Padangan', 48, 'PUSKESMAS', 71);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (140, 'Pamekasan', 46, 'KLINIK', 20);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (141, 'Gambiran', 38, 'KLINIK', 45);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (142, 'Tongas', 155, 'RUMAH SAKIT', 44);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (143, 'Mojokerto', 191, 'RUMAH SAKIT', 69);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (144, 'RA.Basoeni', 9, 'PUSKESMAS', 49);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (145, 'Landak', 48, 'KLINIK', 34);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (146, 'Kab.Bengkayang', 42, 'PUSKESMAS', 28);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (147, 'Sanggau', 43, 'PUSKESMAS', 8);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (148, 'Poso', 4, 'PUSKESMAS', 36);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (149, 'Sukamara', 42, 'PUSKESMAS', 59);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (150, 'Balangan', 17, 'RUMAH SAKIT', 78);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (151, 'Buntok', 60, 'RUMAH SAKIT', 86);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (152, 'Lamandau', 49, 'PUSKESMAS', 56);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (153, 'Tarakan', 37, 'KLINIK', 50);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (154, 'Sangatta', 30, 'KLINIK', 7);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (155, 'Piru', 46, 'KLINIK', 39);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (156, 'Tual', 181, 'RUMAH SAKIT', 41);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (157, 'Namlea', 149, 'RUMAH SAKIT', 47);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (158, 'Ambon', 20, 'KLINIK', 38);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (159, 'Maba', 94, 'RUMAH SAKIT', 75);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (160, 'Weda', 26, 'PUSKESMAS', 11);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (161, 'Jailolo', 6, 'KLINIK', 9);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (162, 'Sanana', 146, 'RUMAH SAKIT', 70);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (163, 'Ternate', 108, 'RUMAH SAKIT', 37);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (164, 'Mataram', 56, 'RUMAH SAKIT', 84);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (165, 'Praya', 14, 'KLINIK', 56);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (166, 'Dompu', 27, 'KLINIK', 45);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (167, 'Raba', 88, 'RUMAH SAKIT', 25);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (168, 'Soe', 148, 'RUMAH SAKIT', 81);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (169, 'Lendemoripa', 47, 'KLINIK', 89);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (170, 'Naibonat', 26, 'KLINIK', 72);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (171, 'Waikabubak', 162, 'RUMAH SAKIT', 92);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (172, 'Waingapu', 11, 'KLINIK', 32);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (173, 'Kefamenanu', 37, 'KLINIK', 21);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (174, 'Belu', 48, 'PUSKESMAS', 89);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (175, 'Alor', 3, 'KLINIK', 95);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (176, 'Larantuka', 38, 'KLINIK', 82);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (177, 'Lewoleba', 14, 'KLINIK', 46);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (178, 'Ende', 26, 'PUSKESMAS', 36);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (179, 'Bajawa', 29, 'KLINIK', 8);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (180, 'Ruteng', 174, 'RUMAH SAKIT', 72);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (181, 'Bhayangkara', 41, 'PUSKESMAS', 47);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (182, 'Oksibil', 50, 'RUMAH SAKIT', 79);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (183, 'Merauke', 39, 'PUSKESMAS', 84);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (184, 'Wamena', 123, 'RUMAH SAKIT', 44);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (185, 'Paniai', 17, 'KLINIK', 1);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (186, 'Serui', 13, 'PUSKESMAS', 100);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (187, 'Kab.Keerom', 20, 'KLINIK', 46);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (188, 'Manokwari', 50, 'PUSKESMAS', 67);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (189, 'Manokwari', 51, 'RUMAH SAKIT', 82);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (190, 'Siak', 35, 'PUSKESMAS', 10);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (191, 'Kec.Mandau', 174, 'RUMAH SAKIT', 17);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (192, 'Bangkinang', 74, 'RUMAH SAKIT', 90);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (193, 'Bengkalis', 18, 'PUSKESMAS', 44);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (194, 'Dumai', 6, 'KLINIK', 70);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (195, 'Polewali', 48, 'PUSKESMAS', 48);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (196, 'Majene', 7, 'PUSKESMAS', 30);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (197, 'Mamuju', 43, 'PUSKESMAS', 11);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (198, 'Palopo', 116, 'RUMAH SAKIT', 69);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (199, 'Enrekang', 49, 'PUSKESMAS', 50);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (200, 'Sinjai', 23, 'PUSKESMAS', 31);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (201, 'Selayar', 13, 'KLINIK', 69);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (202, 'Pangkep', 156, 'RUMAH SAKIT', 84);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (203, 'Barru', 3, 'PUSKESMAS', 13);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (204, 'Daya', 57, 'RUMAH SAKIT', 54);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (205, 'Banggai', 185, 'RUMAH SAKIT', 7);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (206, 'Masyita', 32, 'KLINIK', 89);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (207, 'Bitung', 180, 'RUMAH SAKIT', 84);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (208, 'An-Nisa', 46, 'KLINIK', 23);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (209, 'Arosuka,Solok', 165, 'RUMAH SAKIT', 76);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (210, 'Pariaman', 40, 'KLINIK', 98);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (211, 'Suliki', 11, 'KLINIK', 40);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (212, 'Solok', 14, 'KLINIK', 5);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (213, 'Charitas', 28, 'KLINIK', 100);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (214, 'Lebong', 28, 'KLINIK', 20);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (215, 'Kayuagung', 87, 'RUMAH SAKIT', 74);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (216, 'Lahat', 50, 'KLINIK', 3);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (217, 'Sekayu', 26, 'RUMAH SAKIT', 62);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (218, 'Banyuasin', 13, 'KLINIK', 19);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (219, 'Kabanjahe', 46, 'KLINIK', 43);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (220, 'Natal', 18, 'PUSKESMAS', 93);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (221, 'Delia', 184, 'RUMAH SAKIT', 44);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (222, 'Trianda', 32, 'PUSKESMAS', 33);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (223, 'Panyabungan', 8, 'RUMAH SAKIT', 12);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (224, 'Sipirok', 5, 'KLINIK', 37);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (225, 'Sibuhuan', 42, 'KLINIK', 63);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (226, 'Pandan', 26, 'KLINIK', 79);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (227, 'Tarutung', 175, 'RUMAH SAKIT', 31);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (228, 'Porsea', 7, 'PUSKESMAS', 78);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (229, 'Simalungun', 36, 'PUSKESMAS', 63);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (230, 'Sidikalang', 4, 'PUSKESMAS', 31);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (231, 'Sembiring', 3, 'PUSKESMAS', 29);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (232, 'Sibolga', 4, 'KLINIK', 79);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (233, 'Simeulue', 42, 'KLINIK', 86);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (234, 'Sigli', 133, 'RUMAH SAKIT', 88);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (235, 'Tamiang', 3, 'KLINIK', 24);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (236, 'Langsa', 133, 'RUMAH SAKIT', 84);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (237, 'Kutacane', 2, 'KLINIK', 71);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (238, 'Meuraxa', 32, 'RUMAH SAKIT', 97);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (239, 'Sabang', 5, 'KLINIK', 13);
