insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (1, 'Persahabatan', 36, 'PUSKESMAS', 151);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (2, 'Manuela', 112, 'RUMAH SAKIT', 285);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (3, 'Fatmawati', 49, 'RUMAH SAKIT', 362);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (4, 'MMC', 30, 'PUSKESMAS', 405);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (5, 'Evasari', 47, 'KLINIK', 274);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (6, 'Sukmul', 26, 'PUSKESMAS', 148);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (7, 'Koja', 14, 'KLINIK', 105);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (8, 'Cengkareng', 27, 'PUSKESMAS', 104);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (9, 'Pusdikkes', 48, 'KLINIK', 235);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (10, 'Hermina', 2, 'KLINIK', 90);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (11, 'Yadika', 113, 'RUMAH SAKIT', 232);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (12, 'Tarakan', 53, 'RUMAH SAKIT', 93);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (13, 'Family', 19, 'KLINIK', 280);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (14, 'Mulyasari', 50, 'KLINIK', 134);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (15, 'Amlapura', 89, 'RUMAH SAKIT', 30);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (16, 'Wangaya', 10, 'KLINIK', 378);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (17, 'Negara', 120, 'RUMAH SAKIT', 402);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (18, 'Badung', 35, 'KLINIK', 20);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (19, 'Tabanan', 9, 'PUSKESMAS', 170);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (20, 'Premagana', 40, 'PUSKESMAS', 72);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (21, 'Klungkung', 32, 'KLINIK', 444);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (22, 'Bangli', 41, 'KLINIK', 219);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (23, 'Brebes', 41, 'PUSKESMAS', 44);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (24, 'SELARAS', 48, 'PUSKESMAS', 33);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (25, 'Tiara', 12, 'KLINIK', 251);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (26, 'Mayapada', 25, 'KLINIK', 297);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (27, 'Tidar', 37, 'PUSKESMAS', 257);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (28, 'Roemani', 40, 'RUMAH SAKIT', 465);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (29, 'Dr.Oen', 145, 'RUMAH SAKIT', 344);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (30, 'Kotabaru', 166, 'RUMAH SAKIT', 89);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (31, 'Banjarbaru', 198, 'RUMAH SAKIT', 154);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (32, 'Kab.Sekadau', 34, 'KLINIK', 468);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (33, 'Melawi', 7, 'KLINIK', 200);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (34, 'St.Antonius', 42, 'KLINIK', 8);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (35, 'Sambas', 5, 'KLINIK', 429);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (36, 'Liwa', 197, 'RUMAH SAKIT', 24);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (37, 'Pringsewu', 8, 'PUSKESMAS', 285);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (38, 'Sukadana', 8, 'KLINIK', 331);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (39, 'Dabo', 75, 'RUMAH SAKIT', 233);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (40, 'Natuna', 16, 'KLINIK', 427);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (41, 'Kalianda', 3, 'PUSKESMAS', 122);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (42, 'Kolaka', 16, 'PUSKESMAS', 482);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (43, 'Bombana', 16, 'PUSKESMAS', 131);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (44, 'Wakatobi', 23, 'KLINIK', 381);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (45, 'Namrole', 1, 'PUSKESMAS', 246);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (46, 'Raha', 28, 'PUSKESMAS', 334);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (47, 'Unaaha', 41, 'KLINIK', 432);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (48, 'Noongan', 44, 'PUSKESMAS', 168);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (49, 'Morowali', 74, 'RUMAH SAKIT', 492);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (50, 'Ampana', 2, 'KLINIK', 343);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (51, 'Kabelota', 0, 'KLINIK', 10);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (52, 'Buol', 17, 'RUMAH SAKIT', 488);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (53, 'Tangerang', 3, 'KLINIK', 454);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (54, 'Budiasih', 46, 'KLINIK', 151);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (55, 'Melati', 32, 'RUMAH SAKIT', 199);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (56, 'Kurnia', 45, 'KLINIK', 297);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (57, 'Malingping', 46, 'RUMAH SAKIT', 211);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (58, 'Rafflesia', 43, 'KLINIK', 281);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (59, 'Curup', 12, 'PUSKESMAS', 433);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (60, 'Mukomuko', 34, 'PUSKESMAS', 344);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (61, 'Manna', 108, 'RUMAH SAKIT', 26);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (62, 'Muaradua', 48, 'RUMAH SAKIT', 265);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (63, 'Kepahiang', 19, 'KLINIK', 320);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (64, 'Wates', 4, 'PUSKESMAS', 490);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (65, 'Prambanan', 29, 'RUMAH SAKIT', 304);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (66, 'Wonosari', 161, 'RUMAH SAKIT', 272);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (67, 'Sleman', 21, 'KLINIK', 497);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (68, 'Tombulilato', 45, 'PUSKESMAS', 209);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (69, 'Pohuwato', 38, 'KLINIK', 84);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (70, 'Karawang', 47, 'KLINIK', 446);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (71, 'Meilia', 18, 'KLINIK', 224);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (72, 'Cianjur', 45, 'KLINIK', 497);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (73, 'Pandeglang', 34, 'KLINIK', 139);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (74, 'Ciawi', 41, 'KLINIK', 13);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (75, 'Indramayu', 28, 'KLINIK', 268);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (76, 'Cibinong', 28, 'PUSKESMAS', 235);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (77, 'Waled', 35, 'PUSKESMAS', 12);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (78, 'Bekasi', 26, 'PUSKESMAS', 496);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (79, 'Kebonjati', 32, 'RUMAH SAKIT', 430);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (80, 'Sekarwangi', 30, 'KLINIK', 198);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (81, 'Cimacan', 112, 'RUMAH SAKIT', 259);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (82, 'Majalaya', 30, 'PUSKESMAS', 145);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (83, 'Cibabat', 23, 'PUSKESMAS', 100);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (84, 'Soreang', 65, 'RUMAH SAKIT', 36);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (85, 'Tasikmalaya', 143, 'RUMAH SAKIT', 110);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (86, 'Ciamis', 33, 'KLINIK', 90);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (87, 'Banjar', 127, 'RUMAH SAKIT', 432);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (88, 'Kuningan', 17, 'PUSKESMAS', 269);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (89, 'Sidawangi', 0, 'RUMAH SAKIT', 264);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (90, 'Arjawinangun', 131, 'RUMAH SAKIT', 400);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (91, 'Majalengka', 157, 'RUMAH SAKIT', 456);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (92, 'Cideres', 44, 'RUMAH SAKIT', 39);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (93, 'Sumedang', 8, 'PUSKESMAS', 175);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (94, 'Subang', 18, 'PUSKESMAS', 485);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (95, 'Medika', 9, 'KLINIK', 38);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (96, 'Ananda', 30, 'KLINIK', 33);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (97, 'Kab.Bekasi', 21, 'RUMAH SAKIT', 278);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (98, 'Sragen', 5, 'KLINIK', 137);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (99, 'Majenang', 16, 'PUSKESMAS', 323);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (100, 'Banjarnegara', 50, 'PUSKESMAS', 494);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (101, 'Banyudono', 26, 'PUSKESMAS', 155);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (102, 'Pekalongan', 0, 'PUSKESMAS', 105);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (103, 'Cilacap', 4, 'PUSKESMAS', 278);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (104, 'Wonosobo', 76, 'RUMAH SAKIT', 366);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (105, 'Amanah', 50, 'RUMAH SAKIT', 338);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (106, 'Banyumas', 39, 'RUMAH SAKIT', 491);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (107, 'Ajibarang', 134, 'RUMAH SAKIT', 84);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (108, 'Purbalinnga', 23, 'PUSKESMAS', 267);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (109, 'Nirmala', 84, 'RUMAH SAKIT', 251);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (110, 'Kebumen', 37, 'RUMAH SAKIT', 339);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (111, 'Simo', 23, 'KLINIK', 116);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (112, 'Sujoharjo', 40, 'RUMAH SAKIT', 237);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (113, 'Karanganyar', 46, 'PUSKESMAS', 114);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (114, 'Assalam', 10, 'PUSKESMAS', 74);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (115, 'Blora', 15, 'PUSKESMAS', 469);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (116, 'Pati', 154, 'RUMAH SAKIT', 43);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (117, 'Kudus', 3, 'RUMAH SAKIT', 199);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (118, 'Kudus', 179, 'RUMAH SAKIT', 353);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (119, 'Ambarawa', 4, 'PUSKESMAS', 250);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (120, 'Ungaran', 174, 'RUMAH SAKIT', 73);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (121, 'Kardinah', 35, 'PUSKESMAS', 406);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (122, '&quot;Kanjuruhan&quot;Kepanjen', 5, 'KLINIK', 173);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (123, 'Lawang', 18, 'RUMAH SAKIT', 316);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (124, 'Genteng', 3, 'KLINIK', 479);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (125, 'Sumberrejo', 46, 'PUSKESMAS', 433);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (126, 'Al-irsyad', 53, 'RUMAH SAKIT', 490);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (127, 'PHC', 2, 'PUSKESMAS', 218);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (128, 'An-Nisaa', 36, 'PUSKESMAS', 161);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (129, 'Blambangan', 97, 'RUMAH SAKIT', 512);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (130, 'Pare', 0, 'KLINIK', 456);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (131, 'Jember', 29, 'PUSKESMAS', 400);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (132, 'Balung', 16, 'PUSKESMAS', 169);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (133, 'Bangil', 15, 'PUSKESMAS', 321);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (134, 'Sidoarjo', 35, 'PUSKESMAS', 470);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (135, 'Muslimat', 28, 'KLINIK', 133);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (136, 'Nganjuk', 35, 'PUSKESMAS', 371);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (137, 'Kertosono', 16, 'KLINIK', 262);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (138, 'Dungus', 44, 'KLINIK', 285);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (139, 'Padangan', 35, 'RUMAH SAKIT', 26);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (140, 'Pamekasan', 48, 'KLINIK', 300);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (141, 'Gambiran', 111, 'RUMAH SAKIT', 163);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (142, 'Tongas', 34, 'RUMAH SAKIT', 103);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (143, 'Mojokerto', 3, 'KLINIK', 311);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (144, 'RA.Basoeni', 17, 'KLINIK', 393);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (145, 'Landak', 25, 'PUSKESMAS', 123);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (146, 'Kab.Bengkayang', 5, 'PUSKESMAS', 109);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (147, 'Sanggau', 14, 'KLINIK', 309);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (148, 'Poso', 56, 'RUMAH SAKIT', 23);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (149, 'Sukamara', 3, 'RUMAH SAKIT', 423);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (150, 'Balangan', 75, 'RUMAH SAKIT', 371);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (151, 'Buntok', 17, 'KLINIK', 315);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (152, 'Lamandau', 10, 'RUMAH SAKIT', 476);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (153, 'Tarakan', 19, 'PUSKESMAS', 457);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (154, 'Sangatta', 33, 'PUSKESMAS', 397);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (155, 'Piru', 18, 'KLINIK', 210);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (156, 'Tual', 162, 'RUMAH SAKIT', 152);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (157, 'Namlea', 25, 'RUMAH SAKIT', 37);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (158, 'Ambon', 28, 'PUSKESMAS', 153);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (159, 'Maba', 44, 'PUSKESMAS', 329);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (160, 'Weda', 41, 'KLINIK', 218);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (161, 'Jailolo', 45, 'KLINIK', 240);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (162, 'Sanana', 22, 'KLINIK', 183);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (163, 'Ternate', 3, 'PUSKESMAS', 78);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (164, 'Mataram', 13, 'PUSKESMAS', 228);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (165, 'Praya', 79, 'RUMAH SAKIT', 489);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (166, 'Dompu', 7, 'RUMAH SAKIT', 416);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (167, 'Raba', 111, 'RUMAH SAKIT', 174);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (168, 'Soe', 45, 'PUSKESMAS', 28);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (169, 'Lendemoripa', 35, 'KLINIK', 272);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (170, 'Naibonat', 11, 'PUSKESMAS', 389);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (171, 'Waikabubak', 141, 'RUMAH SAKIT', 485);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (172, 'Waingapu', 99, 'RUMAH SAKIT', 331);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (173, 'Kefamenanu', 23, 'PUSKESMAS', 1);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (174, 'Belu', 47, 'KLINIK', 62);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (175, 'Alor', 178, 'RUMAH SAKIT', 268);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (176, 'Larantuka', 187, 'RUMAH SAKIT', 2);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (177, 'Lewoleba', 14, 'KLINIK', 421);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (178, 'Ende', 8, 'KLINIK', 423);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (179, 'Bajawa', 18, 'RUMAH SAKIT', 437);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (180, 'Ruteng', 46, 'PUSKESMAS', 48);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (181, 'Bhayangkara', 36, 'KLINIK', 442);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (182, 'Oksibil', 148, 'RUMAH SAKIT', 307);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (183, 'Merauke', 118, 'RUMAH SAKIT', 275);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (184, 'Wamena', 27, 'RUMAH SAKIT', 67);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (185, 'Paniai', 49, 'KLINIK', 489);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (186, 'Serui', 35, 'KLINIK', 212);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (187, 'Kab.Keerom', 104, 'RUMAH SAKIT', 62);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (188, 'Manokwari', 15, 'PUSKESMAS', 468);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (189, 'Manokwari', 1, 'PUSKESMAS', 269);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (190, 'Siak', 78, 'RUMAH SAKIT', 196);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (191, 'Kec.Mandau', 42, 'KLINIK', 318);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (192, 'Bangkinang', 169, 'RUMAH SAKIT', 275);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (193, 'Bengkalis', 107, 'RUMAH SAKIT', 45);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (194, 'Dumai', 28, 'KLINIK', 399);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (195, 'Polewali', 24, 'KLINIK', 47);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (196, 'Majene', 13, 'PUSKESMAS', 381);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (197, 'Mamuju', 37, 'PUSKESMAS', 193);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (198, 'Palopo', 46, 'KLINIK', 210);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (199, 'Enrekang', 193, 'RUMAH SAKIT', 373);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (200, 'Sinjai', 40, 'PUSKESMAS', 203);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (201, 'Selayar', 64, 'RUMAH SAKIT', 281);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (202, 'Pangkep', 25, 'KLINIK', 101);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (203, 'Barru', 15, 'PUSKESMAS', 16);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (204, 'Daya', 44, 'RUMAH SAKIT', 102);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (205, 'Banggai', 13, 'KLINIK', 217);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (206, 'Masyita', 34, 'RUMAH SAKIT', 190);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (207, 'Bitung', 140, 'RUMAH SAKIT', 432);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (208, 'An-Nisa', 24, 'PUSKESMAS', 160);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (209, 'Arosuka,Solok', 137, 'RUMAH SAKIT', 115);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (210, 'Pariaman', 56, 'RUMAH SAKIT', 223);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (211, 'Suliki', 91, 'RUMAH SAKIT', 334);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (212, 'Solok', 50, 'PUSKESMAS', 318);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (213, 'Charitas', 0, 'RUMAH SAKIT', 354);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (214, 'Lebong', 31, 'PUSKESMAS', 332);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (215, 'Kayuagung', 42, 'PUSKESMAS', 241);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (216, 'Lahat', 45, 'KLINIK', 416);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (217, 'Sekayu', 42, 'KLINIK', 357);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (218, 'Banyuasin', 29, 'KLINIK', 160);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (219, 'Kabanjahe', 42, 'PUSKESMAS', 7);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (220, 'Natal', 1, 'RUMAH SAKIT', 357);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (221, 'Delia', 197, 'RUMAH SAKIT', 25);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (222, 'Trianda', 20, 'PUSKESMAS', 107);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (223, 'Panyabungan', 48, 'RUMAH SAKIT', 504);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (224, 'Sipirok', 35, 'KLINIK', 110);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (225, 'Sibuhuan', 10, 'KLINIK', 479);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (226, 'Pandan', 174, 'RUMAH SAKIT', 406);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (227, 'Tarutung', 7, 'KLINIK', 261);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (228, 'Porsea', 99, 'RUMAH SAKIT', 149);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (229, 'Simalungun', 58, 'RUMAH SAKIT', 430);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (230, 'Sidikalang', 162, 'RUMAH SAKIT', 20);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (231, 'Sembiring', 8, 'KLINIK', 493);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (232, 'Sibolga', 43, 'PUSKESMAS', 501);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (233, 'Simeulue', 51, 'RUMAH SAKIT', 171);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (234, 'Sigli', 40, 'PUSKESMAS', 82);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (235, 'Tamiang', 27, 'RUMAH SAKIT', 162);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (236, 'Langsa', 35, 'KLINIK', 417);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (237, 'Kutacane', 44, 'PUSKESMAS', 256);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (238, 'Meuraxa', 43, 'KLINIK', 413);
insert into "FasilitasKesehatan" ("IDFasilitas", "Nama", "KapasitasHarian", "Tipe", "IDKotaKabupaten") values (239, 'Sabang', 30, 'PUSKESMAS', 496);
