insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Banda Aceh', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Sabang', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Lhokseumawe', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Langsa', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Subulussalam', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Selatan', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Tenggara', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Timur', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Tengah', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Barat', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Besar', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pidie', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Utara', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Simeulue', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Singkil', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bireun', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Barat Daya', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Gayo Lues', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Jaya', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nagan Raya', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Aceh Tamiang', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bener Meriah', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pidie Jaya', 1);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Medan', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Pematang Siantar', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Sibolga', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tanjung Balai', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Binjai', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tebing Tinggi', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Padang Sidempuan', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Gunung Sitoli', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Serdang Bedagai', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Samosir ', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Humbang Hasundutan', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pakpak Bharat', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nias Selatan', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mandailing Natal', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Toba Samosir', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Dairi', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Labuhan Batu', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Asahan', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Simalungun', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Deli Serdang', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Karo', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Langkat', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nias', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tapanuli Selatan', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tapanuli Utara', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tapanuli Tengah', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Batu Bara', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Padang Lawas Utara', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Padang Lawas', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Labuhanbatu Selatan', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Labuhanbatu Utara', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nias Utara', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nias Barat', 34);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Padang', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Solok', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Sawhlunto', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Padang Panjang', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bukittinggi', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Payakumbuh', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Pariaman', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pasaman Barat', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Solok Selatan', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Dharmasraya', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Mentawai', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pasaman', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lima Puluh Kota', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Agam', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Padang Pariaman', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tanah Datar', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sijunjung', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Solok', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pesisir Selatan', 32);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Pekan Baru', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Dumai', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Meranti', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kuantan Singingi', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Siak', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Rokan Hilir', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Rokan Hulu', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pelalawan', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Indragiri Hilir', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bengkalis', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Indragiri Hulu', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kampar', 26);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Jambi', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Sungai Penuh', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tebo', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bungo', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tanjung Jabung Timur', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tanjung Jabung Barat', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Muaro Jambi', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Batanghari', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sarolangun', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Merangin', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kerinci', 8);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Palembang', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Pagar Alam', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Lubuk Linggau', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Prabumulih', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Musi Rawas Utara', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Penukal Abab Lematang Ilir', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Empat Lawang', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ogan Ilir ', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ogan Komering Ulu Selatan ', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ogan Komering Ulu Timur ', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Banyuasin', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Musi Banyuasin', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Musi Rawas', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lahat', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Muara Enim', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ogan Komering Ilir', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ogan Komering Ulu', 33);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bengkulu', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bengkulu Tengah', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepahiang ', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lebong', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Muko Muko', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Seluma', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kaur', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bengkulu Utara', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Rejang Lebong', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bengkulu Selatan', 4);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bandar Lampung', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Metro', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pesisir Barat', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tulangbawang Barat', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mesuji', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pringsewu', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pesawaran', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Way Kanan', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lampung Timur', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tanggamus', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tulang Bawang', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lampung Barat', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lampung Utara', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lampung Tengah', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lampung Selatan', 19);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Pangkal Pinang', 17);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Belitung Timur', 17);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bangka Barat', 17);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bangka Tengah', 17);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bangka Selatan', 17);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Belitung', 17);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bangka', 17);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Batam', 18);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tanjung Pinang', 18);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Anambas', 18);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lingga ', 18);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Natuna', 18);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Karimun', 18);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bintan', 18);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Jakarta Timur', 6);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Jakarta Selatan', 6);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Jakarta Barat', 6);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Jakarta Utara', 6);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Jakarta Pusat', 6);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Seribu', 6);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bandung', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Banjar', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tasikmalaya', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Cimahi', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Depok', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bekasi', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Cirebon', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Sukabumi', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bogor', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pangandaran', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bandung Barat', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bekasi', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Karawang', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Purwakarta', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Subang', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Indramayu', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sumedang', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Majalengka', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Cirebon', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kuningan', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ciamis', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tasikmalaya', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Garut', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bandung', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Cianjur', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sukabumi', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bogor', 9);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Semarang', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tegal', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Pekalongan', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Salatiga', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Surakarta', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Magelang', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Brebes', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tegal', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pemalang', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pekalongan', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Batang', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kendal', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Temanggung', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Semarang', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Demak', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Jepara', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kudus', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pati', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Rembang', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Blora', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Grobogan', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sragen', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Karanganyar', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Wonogiri', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sukoharjo', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Klaten', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Boyolali', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Magelang', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Wonosobo', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Purworejo', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kebumen', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Banjarnegara', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Purbalingga', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Banyumas', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Cilacap', 10);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Yogyakarta', 5);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sleman', 5);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Gunung Kidul', 5);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bantul', 5);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kulon Progo', 5);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Surabaya', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Batu', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Madiun', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Mojokerto', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Pasuruan', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Probolinggo', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Malang', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Blitar', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Kediri', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sumenep', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pamekasan', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sampang', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bangkalan', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Gresik', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lamongan', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tuban', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bojonegoro', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ngawi', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Magetan', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Madiun', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nganjuk', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Jombang', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mojokerto', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sidoarjo', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pasuruan', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Probolinggo', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Situbondo', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bondowoso', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Banyuwangi', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Jember', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lumajang', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Malang', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kediri', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Blitar', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tulungagung', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Trenggalek', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ponorogo', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pacitan', 11);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Serang', 3);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Cilegon', 3);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tangerang', 3);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tangerang Selatan', 3);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Serang', 3);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tangerang', 3);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lebak', 3);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pandeglang', 3);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Denpasar', 2);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Buleleng', 2);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Karangasem', 2);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bangli', 2);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Klungkung', 2);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Gianyar', 2);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Badung', 2);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tabanan', 2);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Jembrana', 2);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Mataram', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bima', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lombok Utara', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sumbawa Barat', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bima', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Dompu', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sumbawa ', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lombok Timur', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lombok Tengah', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lombok Barat', 22);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Kupang', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Malaka', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sabu Raijua', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Manggarai Timur', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sumba Barat Daya', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sumba Tengah', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nagekeo', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Manggarai Barat', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Rote Ndao', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lembata', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sumba Barat', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sumba Timur', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Manggarai', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ngada', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ende', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sikka', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Flores Timur', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Alor', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Belu', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Timor Tengah Utara', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Timor Tengah Selatan', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kupang', 23);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Pontianak', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Singkawang', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kubu Raya', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kayong Utara', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sekadau', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Melawi', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Landak', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bengkayang', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kapuas Hulu', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sintang ', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Ketapang', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sanggau ', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mempawah', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sambas', 12);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Palangkaraya', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Barito Timur', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Murung Raya', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pulang Pisau', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Gunung Mas', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lamandau', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sukamara', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Seruyan', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Katingan', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Barito Utara', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Barito Selatan', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kapuas', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kotawaringin Timur', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kotawaringin Barat', 14);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Banjarmasin', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Banjarbaru', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Balangan', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tanah Bambu', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tabalong', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Hulu Sungai Utara', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Hulu Sungai Tengah', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Hulu Sungai Selatan', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tapin', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Barito Kuala', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Banjar', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kotabaru', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tanah Laut', 13);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Samarinda', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bontang', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Balikpapan', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mahakam Ulu', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Penajam Paser Utara', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kutai Timur', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kutai Barat', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Berau', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kutai Kertanegara', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Paser', 15);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tarakan', 16);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tana Tidung', 16);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nunukan', 16);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Malinau', 16);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bulungan', 16);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Manado', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tomohon', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bitung', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Kotamobagu', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bolaang Mangondow Selatan', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bolaang Mangondow Timur', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Siau Tagulandang Biaro', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bolaang Mangondow Utara', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Minahasa Tenggara', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Minahasa Utara', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Minahasa Selatan', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Talaud', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Sangihe', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Minahasa', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bolaang Mangondow', 31);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Palu', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Morowali Utara', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Banggai Laut', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sigi', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tojo Una-Una', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Parigi Moutong', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Banggai Kepulauan', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Morowali', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Buol', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Toli-Toli', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Donggala', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Poso', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Banggai', 29);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Makasar', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Palopo', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Pare Pare', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Toraja Utara', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Luwu Timur', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Luwu Utara', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tana Toraja', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Luwu', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Enrekang', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pinrang', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sidenreng Rappang', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Wajo', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Soppeng', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Barru', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pangkajene Kepulauan', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Maros', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bone', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sinjai', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Gowa', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Takalar', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Jeneponto', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bantaeng', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bulukumba', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Selayar', 28);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Kendari', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Bau Bau', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Buton Selatan', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Buton Tengah', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Muna Barat', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Konawe Kepulauan', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kolaka Timur', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Buton Utara', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Konawe Utara', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kolaka Utara', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Wakatobi', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bombana', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Konawe Selatan', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Buton', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Muna', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Konawe', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kolaka', 30);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Gorontalo', 7);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pohuwato', 7);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Bone Bolango', 7);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Boalemo', 7);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Gorontalo', 7);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Gorontalo Utara', 7);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Majene', 27);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Polowali Mandar', 27);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mamasa', 27);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mamuju', 27);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mamuju Utara', 27);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mamuju Tengah', 27);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Ambon', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tual', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Buru Selatan', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Maluku Barat Daya', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Aru', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Seram Bagian Barat ', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Seram Bagian Timur', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Buru', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Maluku Tenggara Barat', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Maluku Tenggara', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Maluku Tengah', 20);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Ternate', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Tidore Kepulauan', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pulau Taliabu', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pulau Morotai', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Halmahera Timur', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Sula', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Halmahera Selatan', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Halmahera Utara', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Halmahera Tengah', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Halmahera Barat', 21);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Jayapura', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Deiyai', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Intan Jaya', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Dogiyai', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Puncak', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nduga', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Lanny Jaya', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Yalimo', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mamberamo Tengah', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mamberamo Raya', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Supiori', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Asmat', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mappi', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Boven Digoel', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Waropen', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tolikara', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Yahukimo', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pegunungan Bintang', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Keerom', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sarmi', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Mimika', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Paniai', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Puncak Jaya', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Biak Numfor', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kepulauan Yapen', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Nabire', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Jayapura', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Jayawijaya', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Merauke', 24);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kota Sorong', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Pegunungan Arfak', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Manokwari Selatan', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Maybrat', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Tambrauw', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Kaimana', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Teluk Wondama', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Teluk Bintuni', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Raja Ampat', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sorong Selatan', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Fak Fak', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Manokwari', 25);
insert into "KotaKabupaten" ("Nama", "IDProvinsi") values ('Kabupaten Sorong', 25);
