insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (1, 'Persahabatan', 22, 'KLINIK', 418);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (2, 'Manuela', 12, 'KLINIK', 510);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (3, 'Fatmawati', 2, 'KLINIK', 409);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (4, 'MMC', 21, 'PUSKESMAS', 260);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (5, 'Evasari', 42, 'RUMAH SAKIT', 367);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (6, 'Sukmul', 9, 'PUSKESMAS', 404);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (7, 'Koja', 61, 'RUMAH SAKIT', 86);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (8, 'Cengkareng', 24, 'PUSKESMAS', 157);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (9, 'Pusdikkes', 34, 'KLINIK', 206);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (10, 'Hermina', 93, 'RUMAH SAKIT', 274);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (11, 'Yadika', 36, 'PUSKESMAS', 249);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (12, 'Tarakan', 141, 'RUMAH SAKIT', 437);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (13, 'Family', 19, 'PUSKESMAS', 236);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (14, 'Mulyasari', 199, 'RUMAH SAKIT', 364);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (15, 'Amlapura', 173, 'RUMAH SAKIT', 149);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (16, 'Wangaya', 2, 'KLINIK', 476);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (17, 'Negara', 96, 'RUMAH SAKIT', 208);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (18, 'Badung', 8, 'KLINIK', 290);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (19, 'Tabanan', 34, 'RUMAH SAKIT', 222);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (20, 'Premagana', 18, 'KLINIK', 484);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (21, 'Klungkung', 28, 'PUSKESMAS', 482);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (22, 'Bangli', 132, 'RUMAH SAKIT', 73);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (23, 'Brebes', 47, 'KLINIK', 374);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (24, 'SELARAS', 11, 'PUSKESMAS', 487);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (25, 'Tiara', 38, 'PUSKESMAS', 286);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (26, 'Mayapada', 10, 'KLINIK', 263);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (27, 'Tidar', 46, 'PUSKESMAS', 389);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (28, 'Roemani', 47, 'PUSKESMAS', 396);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (29, 'Dr.Oen', 16, 'KLINIK', 466);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (30, 'Kotabaru', 112, 'RUMAH SAKIT', 157);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (31, 'Banjarbaru', 88, 'RUMAH SAKIT', 304);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (32, 'Kab.Sekadau', 40, 'PUSKESMAS', 241);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (33, 'Melawi', 10, 'RUMAH SAKIT', 222);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (34, 'St.Antonius', 66, 'RUMAH SAKIT', 401);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (35, 'Sambas', 49, 'KLINIK', 112);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (36, 'Liwa', 91, 'RUMAH SAKIT', 318);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (37, 'Pringsewu', 18, 'KLINIK', 277);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (38, 'Sukadana', 160, 'RUMAH SAKIT', 73);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (39, 'Dabo', 25, 'KLINIK', 480);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (40, 'Natuna', 47, 'RUMAH SAKIT', 420);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (41, 'Kalianda', 49, 'PUSKESMAS', 97);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (42, 'Kolaka', 46, 'PUSKESMAS', 466);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (43, 'Bombana', 33, 'RUMAH SAKIT', 127);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (44, 'Wakatobi', 1, 'KLINIK', 202);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (45, 'Namrole', 10, 'KLINIK', 180);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (46, 'Raha', 14, 'PUSKESMAS', 387);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (47, 'Unaaha', 22, 'RUMAH SAKIT', 142);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (48, 'Noongan', 43, 'KLINIK', 28);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (49, 'Morowali', 21, 'KLINIK', 465);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (50, 'Ampana', 17, 'PUSKESMAS', 269);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (51, 'Kabelota', 37, 'PUSKESMAS', 158);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (52, 'Buol', 35, 'KLINIK', 394);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (53, 'Tangerang', 6, 'PUSKESMAS', 413);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (54, 'Budiasih', 51, 'RUMAH SAKIT', 102);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (55, 'Melati', 27, 'KLINIK', 294);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (56, 'Kurnia', 127, 'RUMAH SAKIT', 335);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (57, 'Malingping', 2, 'PUSKESMAS', 40);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (58, 'Rafflesia', 34, 'KLINIK', 508);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (59, 'Curup', 47, 'KLINIK', 394);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (60, 'Mukomuko', 12, 'KLINIK', 200);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (61, 'Manna', 50, 'PUSKESMAS', 106);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (62, 'Muaradua', 109, 'RUMAH SAKIT', 285);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (63, 'Kepahiang', 24, 'KLINIK', 123);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (64, 'Wates', 76, 'RUMAH SAKIT', 171);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (65, 'Prambanan', 45, 'PUSKESMAS', 34);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (66, 'Wonosari', 190, 'RUMAH SAKIT', 32);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (67, 'Sleman', 47, 'PUSKESMAS', 257);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (68, 'Tombulilato', 68, 'RUMAH SAKIT', 181);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (69, 'Pohuwato', 68, 'RUMAH SAKIT', 168);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (70, 'Karawang', 50, 'KLINIK', 197);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (71, 'Meilia', 19, 'PUSKESMAS', 370);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (72, 'Cianjur', 22, 'PUSKESMAS', 263);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (73, 'Pandeglang', 22, 'KLINIK', 447);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (74, 'Ciawi', 68, 'RUMAH SAKIT', 273);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (75, 'Indramayu', 37, 'KLINIK', 260);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (76, 'Cibinong', 94, 'RUMAH SAKIT', 372);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (77, 'Waled', 6, 'KLINIK', 286);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (78, 'Bekasi', 9, 'RUMAH SAKIT', 295);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (79, 'Kebonjati', 10, 'PUSKESMAS', 515);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (80, 'Sekarwangi', 127, 'RUMAH SAKIT', 397);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (81, 'Cimacan', 40, 'KLINIK', 283);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (82, 'Majalaya', 40, 'PUSKESMAS', 392);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (83, 'Cibabat', 35, 'PUSKESMAS', 367);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (84, 'Soreang', 176, 'RUMAH SAKIT', 152);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (85, 'Tasikmalaya', 77, 'RUMAH SAKIT', 437);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (86, 'Ciamis', 36, 'KLINIK', 398);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (87, 'Banjar', 32, 'PUSKESMAS', 8);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (88, 'Kuningan', 20, 'PUSKESMAS', 31);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (89, 'Sidawangi', 81, 'RUMAH SAKIT', 291);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (90, 'Arjawinangun', 28, 'PUSKESMAS', 47);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (91, 'Majalengka', 36, 'KLINIK', 325);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (92, 'Cideres', 7, 'KLINIK', 176);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (93, 'Sumedang', 4, 'PUSKESMAS', 165);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (94, 'Subang', 167, 'RUMAH SAKIT', 144);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (95, 'Medika', 14, 'PUSKESMAS', 175);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (96, 'Ananda', 42, 'PUSKESMAS', 491);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (97, 'Kab.Bekasi', 186, 'RUMAH SAKIT', 437);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (98, 'Sragen', 42, 'RUMAH SAKIT', 67);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (99, 'Majenang', 81, 'RUMAH SAKIT', 309);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (100, 'Banjarnegara', 103, 'RUMAH SAKIT', 172);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (101, 'Banyudono', 17, 'PUSKESMAS', 470);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (102, 'Pekalongan', 12, 'PUSKESMAS', 180);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (103, 'Cilacap', 8, 'PUSKESMAS', 493);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (104, 'Wonosobo', 16, 'PUSKESMAS', 228);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (105, 'Amanah', 33, 'PUSKESMAS', 193);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (106, 'Banyumas', 46, 'KLINIK', 176);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (107, 'Ajibarang', 17, 'PUSKESMAS', 283);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (108, 'Purbalinnga', 9, 'KLINIK', 210);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (109, 'Nirmala', 8, 'PUSKESMAS', 150);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (110, 'Kebumen', 48, 'KLINIK', 78);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (111, 'Simo', 119, 'RUMAH SAKIT', 158);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (112, 'Sujoharjo', 0, 'KLINIK', 469);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (113, 'Karanganyar', 23, 'KLINIK', 442);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (114, 'Assalam', 13, 'KLINIK', 103);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (115, 'Blora', 18, 'RUMAH SAKIT', 397);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (116, 'Pati', 47, 'RUMAH SAKIT', 503);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (117, 'Kudus', 7, 'PUSKESMAS', 109);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (118, 'Kudus', 111, 'RUMAH SAKIT', 330);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (119, 'Ambarawa', 6, 'KLINIK', 480);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (120, 'Ungaran', 26, 'PUSKESMAS', 171);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (121, 'Kardinah', 3, 'PUSKESMAS', 3);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (122, '&quot;Kanjuruhan&quot;Kepanjen', 7, 'PUSKESMAS', 278);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (123, 'Lawang', 26, 'KLINIK', 512);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (124, 'Genteng', 156, 'RUMAH SAKIT', 185);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (125, 'Sumberrejo', 34, 'KLINIK', 329);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (126, 'Al-irsyad', 2, 'KLINIK', 120);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (127, 'PHC', 136, 'RUMAH SAKIT', 166);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (128, 'An-Nisaa', 47, 'PUSKESMAS', 257);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (129, 'Blambangan', 9, 'PUSKESMAS', 392);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (130, 'Pare', 135, 'RUMAH SAKIT', 259);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (131, 'Jember', 48, 'PUSKESMAS', 448);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (132, 'Balung', 43, 'PUSKESMAS', 400);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (133, 'Bangil', 105, 'RUMAH SAKIT', 358);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (134, 'Sidoarjo', 22, 'KLINIK', 323);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (135, 'Muslimat', 13, 'PUSKESMAS', 301);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (136, 'Nganjuk', 57, 'RUMAH SAKIT', 427);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (137, 'Kertosono', 141, 'RUMAH SAKIT', 73);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (138, 'Dungus', 41, 'PUSKESMAS', 416);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (139, 'Padangan', 18, 'KLINIK', 325);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (140, 'Pamekasan', 173, 'RUMAH SAKIT', 188);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (141, 'Gambiran', 26, 'RUMAH SAKIT', 264);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (142, 'Tongas', 47, 'KLINIK', 54);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (143, 'Mojokerto', 3, 'KLINIK', 297);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (144, 'RA.Basoeni', 27, 'KLINIK', 430);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (145, 'Landak', 38, 'PUSKESMAS', 218);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (146, 'Kab.Bengkayang', 18, 'PUSKESMAS', 241);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (147, 'Sanggau', 24, 'KLINIK', 313);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (148, 'Poso', 190, 'RUMAH SAKIT', 280);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (149, 'Sukamara', 16, 'KLINIK', 386);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (150, 'Balangan', 106, 'RUMAH SAKIT', 301);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (151, 'Buntok', 131, 'RUMAH SAKIT', 132);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (152, 'Lamandau', 6, 'KLINIK', 74);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (153, 'Tarakan', 146, 'RUMAH SAKIT', 129);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (154, 'Sangatta', 33, 'PUSKESMAS', 431);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (155, 'Piru', 37, 'RUMAH SAKIT', 287);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (156, 'Tual', 16, 'KLINIK', 321);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (157, 'Namlea', 30, 'PUSKESMAS', 352);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (158, 'Ambon', 21, 'RUMAH SAKIT', 317);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (159, 'Maba', 49, 'PUSKESMAS', 291);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (160, 'Weda', 1, 'PUSKESMAS', 147);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (161, 'Jailolo', 50, 'PUSKESMAS', 359);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (162, 'Sanana', 3, 'PUSKESMAS', 359);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (163, 'Ternate', 32, 'KLINIK', 163);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (164, 'Mataram', 37, 'KLINIK', 154);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (165, 'Praya', 190, 'RUMAH SAKIT', 439);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (166, 'Dompu', 31, 'PUSKESMAS', 310);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (167, 'Raba', 38, 'PUSKESMAS', 209);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (168, 'Soe', 5, 'KLINIK', 179);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (169, 'Lendemoripa', 108, 'RUMAH SAKIT', 409);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (170, 'Naibonat', 48, 'PUSKESMAS', 198);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (171, 'Waikabubak', 103, 'RUMAH SAKIT', 44);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (172, 'Waingapu', 1, 'KLINIK', 204);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (173, 'Kefamenanu', 44, 'PUSKESMAS', 231);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (174, 'Belu', 44, 'RUMAH SAKIT', 266);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (175, 'Alor', 49, 'PUSKESMAS', 58);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (176, 'Larantuka', 9, 'PUSKESMAS', 281);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (177, 'Lewoleba', 129, 'RUMAH SAKIT', 317);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (178, 'Ende', 51, 'RUMAH SAKIT', 358);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (179, 'Bajawa', 25, 'PUSKESMAS', 205);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (180, 'Ruteng', 119, 'RUMAH SAKIT', 282);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (181, 'Bhayangkara', 175, 'RUMAH SAKIT', 492);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (182, 'Oksibil', 44, 'PUSKESMAS', 363);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (183, 'Merauke', 24, 'KLINIK', 459);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (184, 'Wamena', 30, 'PUSKESMAS', 510);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (185, 'Paniai', 14, 'PUSKESMAS', 168);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (186, 'Serui', 15, 'PUSKESMAS', 359);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (187, 'Kab.Keerom', 23, 'PUSKESMAS', 36);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (188, 'Manokwari', 4, 'PUSKESMAS', 226);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (189, 'Manokwari', 14, 'KLINIK', 364);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (190, 'Siak', 43, 'KLINIK', 443);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (191, 'Kec.Mandau', 44, 'KLINIK', 432);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (192, 'Bangkinang', 22, 'KLINIK', 38);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (193, 'Bengkalis', 49, 'PUSKESMAS', 460);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (194, 'Dumai', 7, 'PUSKESMAS', 369);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (195, 'Polewali', 22, 'PUSKESMAS', 227);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (196, 'Majene', 25, 'PUSKESMAS', 364);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (197, 'Mamuju', 46, 'KLINIK', 293);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (198, 'Palopo', 45, 'PUSKESMAS', 281);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (199, 'Enrekang', 85, 'RUMAH SAKIT', 174);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (200, 'Sinjai', 0, 'PUSKESMAS', 500);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (201, 'Selayar', 8, 'KLINIK', 93);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (202, 'Pangkep', 109, 'RUMAH SAKIT', 85);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (203, 'Barru', 13, 'KLINIK', 153);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (204, 'Daya', 33, 'KLINIK', 141);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (205, 'Banggai', 45, 'KLINIK', 204);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (206, 'Masyita', 49, 'KLINIK', 279);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (207, 'Bitung', 12, 'PUSKESMAS', 381);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (208, 'An-Nisa', 6, 'PUSKESMAS', 328);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (209, 'Arosuka,Solok', 5, 'RUMAH SAKIT', 440);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (210, 'Pariaman', 17, 'KLINIK', 131);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (211, 'Suliki', 42, 'PUSKESMAS', 95);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (212, 'Solok', 31, 'PUSKESMAS', 268);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (213, 'Charitas', 133, 'RUMAH SAKIT', 12);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (214, 'Lebong', 139, 'RUMAH SAKIT', 3);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (215, 'Kayuagung', 14, 'KLINIK', 381);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (216, 'Lahat', 44, 'RUMAH SAKIT', 505);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (217, 'Sekayu', 31, 'PUSKESMAS', 506);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (218, 'Banyuasin', 8, 'RUMAH SAKIT', 237);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (219, 'Kabanjahe', 173, 'RUMAH SAKIT', 356);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (220, 'Natal', 29, 'PUSKESMAS', 397);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (221, 'Delia', 1, 'PUSKESMAS', 360);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (222, 'Trianda', 14, 'RUMAH SAKIT', 401);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (223, 'Panyabungan', 66, 'RUMAH SAKIT', 111);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (224, 'Sipirok', 22, 'PUSKESMAS', 166);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (225, 'Sibuhuan', 41, 'PUSKESMAS', 479);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (226, 'Pandan', 32, 'PUSKESMAS', 147);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (227, 'Tarutung', 33, 'KLINIK', 37);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (228, 'Porsea', 37, 'KLINIK', 446);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (229, 'Simalungun', 9, 'KLINIK', 127);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (230, 'Sidikalang', 1, 'PUSKESMAS', 44);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (231, 'Sembiring', 41, 'KLINIK', 178);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (232, 'Sibolga', 90, 'RUMAH SAKIT', 196);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (233, 'Simeulue', 10, 'PUSKESMAS', 99);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (234, 'Sigli', 138, 'RUMAH SAKIT', 111);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (235, 'Tamiang', 108, 'RUMAH SAKIT', 379);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (236, 'Langsa', 62, 'RUMAH SAKIT', 423);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (237, 'Kutacane', 159, 'RUMAH SAKIT', 259);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (238, 'Meuraxa', 26, 'PUSKESMAS', 378);
insert into `FasilitasKesehatan` (`IDFasilitas`, `Nama`, `KapasitasHarian`, `Tipe`, `IDKotaKabupaten`) values (239, 'Sabang', 180, 'RUMAH SAKIT', 199);
