insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (1, 'SHIPPED', '2021-08-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (2, 'SHIPPED', '2021-06-11');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (3, 'SHIPPED', '2021-08-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (4, 'SHIPPED', '2021-04-09');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (5, 'SHIPPED', '2021-11-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (6, 'SHIPPED', '2021-07-29');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (7, 'SHIPPED', '2021-11-13');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (8, 'SHIPPED', '2021-05-24');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (9, 'SHIPPED', '2021-09-03');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (10, 'SHIPPED', '2021-06-14');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (11, 'SHIPPED', '2021-09-02');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (12, 'SHIPPED', '2021-08-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (13, 'SHIPPED', '2021-09-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (14, 'SHIPPED', '2021-05-27');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (15, 'SHIPPED', '2022-03-22');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (16, 'SHIPPED', '2021-09-09');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (17, 'SHIPPED', '2021-05-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (18, 'SHIPPED', '2021-08-15');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (19, 'SHIPPED', '2021-08-31');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (20, 'SHIPPED', '2021-11-12');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (21, 'SHIPPED', '2021-10-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (22, 'SHIPPED', '2021-08-16');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (23, 'SHIPPED', '2021-06-09');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (24, 'SHIPPED', '2021-12-09');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (25, 'SHIPPED', '2022-02-06');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (26, 'SHIPPED', '2022-02-24');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (27, 'SHIPPED', '2021-11-23');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (28, 'SHIPPED', '2022-03-18');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (29, 'SHIPPED', '2021-06-03');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (30, 'SHIPPED', '2022-01-08');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (31, 'SHIPPED', '2021-05-20');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (32, 'SHIPPED', '2021-11-13');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (33, 'SHIPPED', '2021-09-27');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (34, 'SHIPPED', '2022-02-09');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (34, 'OUT FOR DELIVERY', '2022-04-07');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (35, 'SHIPPED', '2021-11-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (35, 'OUT FOR DELIVERY', '2022-01-30');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (36, 'SHIPPED', '2021-11-05');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (36, 'OUT FOR DELIVERY', '2022-01-03');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (37, 'SHIPPED', '2021-04-30');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (37, 'OUT FOR DELIVERY', '2021-08-15');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (38, 'SHIPPED', '2022-01-01');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (38, 'OUT FOR DELIVERY', '2022-04-01');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (39, 'SHIPPED', '2022-02-12');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (39, 'OUT FOR DELIVERY', '2022-03-07');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (40, 'SHIPPED', '2021-08-11');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (40, 'OUT FOR DELIVERY', '2022-03-15');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (41, 'SHIPPED', '2022-04-05');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (41, 'OUT FOR DELIVERY', '2022-04-06');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (42, 'SHIPPED', '2021-11-05');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (42, 'OUT FOR DELIVERY', '2022-01-28');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (43, 'SHIPPED', '2021-07-15');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (43, 'OUT FOR DELIVERY', '2022-03-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (44, 'SHIPPED', '2021-09-05');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (44, 'OUT FOR DELIVERY', '2022-01-28');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (45, 'SHIPPED', '2021-11-24');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (45, 'OUT FOR DELIVERY', '2022-02-13');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (46, 'SHIPPED', '2021-08-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (46, 'OUT FOR DELIVERY', '2022-01-23');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (47, 'SHIPPED', '2021-07-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (47, 'OUT FOR DELIVERY', '2022-04-02');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (48, 'SHIPPED', '2021-10-11');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (48, 'OUT FOR DELIVERY', '2021-12-23');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (49, 'SHIPPED', '2022-03-16');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (49, 'OUT FOR DELIVERY', '2022-03-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (50, 'SHIPPED', '2021-08-25');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (50, 'OUT FOR DELIVERY', '2022-04-02');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (51, 'SHIPPED', '2022-02-16');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (51, 'OUT FOR DELIVERY', '2022-02-28');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (52, 'SHIPPED', '2022-01-07');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (52, 'OUT FOR DELIVERY', '2022-02-03');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (53, 'SHIPPED', '2021-09-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (53, 'OUT FOR DELIVERY', '2021-11-04');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (54, 'SHIPPED', '2021-08-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (54, 'OUT FOR DELIVERY', '2022-02-27');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (55, 'SHIPPED', '2021-10-06');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (55, 'OUT FOR DELIVERY', '2021-12-12');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (56, 'SHIPPED', '2021-07-12');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (56, 'OUT FOR DELIVERY', '2021-11-16');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (57, 'SHIPPED', '2021-07-04');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (57, 'OUT FOR DELIVERY', '2021-07-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (58, 'SHIPPED', '2022-03-29');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (58, 'OUT FOR DELIVERY', '2022-04-05');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (59, 'SHIPPED', '2021-07-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (59, 'OUT FOR DELIVERY', '2021-12-20');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (60, 'SHIPPED', '2021-08-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (60, 'OUT FOR DELIVERY', '2022-01-29');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (61, 'SHIPPED', '2021-10-27');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (61, 'OUT FOR DELIVERY', '2022-02-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (62, 'SHIPPED', '2022-01-02');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (62, 'OUT FOR DELIVERY', '2022-01-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (63, 'SHIPPED', '2022-01-30');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (63, 'OUT FOR DELIVERY', '2022-02-13');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (64, 'SHIPPED', '2021-11-09');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (64, 'OUT FOR DELIVERY', '2021-12-23');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (65, 'SHIPPED', '2021-08-17');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (65, 'OUT FOR DELIVERY', '2021-10-16');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (66, 'SHIPPED', '2021-11-22');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (66, 'OUT FOR DELIVERY', '2022-01-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (67, 'SHIPPED', '2021-06-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (67, 'OUT FOR DELIVERY', '2021-08-12');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (67, 'DELIVERED', '2021-09-22');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (68, 'SHIPPED', '2021-06-23');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (68, 'OUT FOR DELIVERY', '2021-07-15');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (68, 'DELIVERED', '2022-01-03');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (69, 'SHIPPED', '2021-06-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (69, 'OUT FOR DELIVERY', '2021-08-22');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (69, 'DELIVERED', '2021-10-20');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (70, 'SHIPPED', '2022-01-01');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (70, 'OUT FOR DELIVERY', '2022-02-25');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (70, 'DELIVERED', '2022-03-11');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (71, 'SHIPPED', '2022-02-22');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (71, 'OUT FOR DELIVERY', '2022-03-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (71, 'DELIVERED', '2022-04-07');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (72, 'SHIPPED', '2021-04-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (72, 'OUT FOR DELIVERY', '2021-06-25');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (72, 'DELIVERED', '2021-11-02');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (73, 'SHIPPED', '2021-12-08');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (73, 'OUT FOR DELIVERY', '2022-03-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (73, 'DELIVERED', '2022-03-31');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (74, 'SHIPPED', '2021-10-18');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (74, 'OUT FOR DELIVERY', '2021-12-24');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (74, 'DELIVERED', '2022-01-29');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (75, 'SHIPPED', '2021-11-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (75, 'OUT FOR DELIVERY', '2022-01-17');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (75, 'DELIVERED', '2022-03-16');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (76, 'SHIPPED', '2021-06-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (76, 'OUT FOR DELIVERY', '2021-12-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (76, 'DELIVERED', '2022-02-16');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (77, 'SHIPPED', '2021-07-09');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (77, 'OUT FOR DELIVERY', '2021-07-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (77, 'DELIVERED', '2022-03-15');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (78, 'SHIPPED', '2021-07-31');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (78, 'OUT FOR DELIVERY', '2021-08-11');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (78, 'DELIVERED', '2022-03-09');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (79, 'SHIPPED', '2021-11-20');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (79, 'OUT FOR DELIVERY', '2021-11-29');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (79, 'DELIVERED', '2022-04-03');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (80, 'SHIPPED', '2021-10-17');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (80, 'OUT FOR DELIVERY', '2021-10-17');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (80, 'DELIVERED', '2022-01-14');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (81, 'SHIPPED', '2021-07-13');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (81, 'OUT FOR DELIVERY', '2021-11-18');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (81, 'DELIVERED', '2022-01-13');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (82, 'SHIPPED', '2022-03-15');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (82, 'OUT FOR DELIVERY', '2022-03-27');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (82, 'DELIVERED', '2022-04-08');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (83, 'SHIPPED', '2021-10-02');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (83, 'OUT FOR DELIVERY', '2021-11-05');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (83, 'DELIVERED', '2021-11-17');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (84, 'SHIPPED', '2021-05-03');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (84, 'OUT FOR DELIVERY', '2021-11-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (84, 'DELIVERED', '2022-01-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (85, 'SHIPPED', '2021-09-15');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (85, 'OUT FOR DELIVERY', '2021-11-04');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (85, 'DELIVERED', '2022-01-31');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (86, 'SHIPPED', '2021-09-25');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (86, 'OUT FOR DELIVERY', '2021-11-29');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (86, 'DELIVERED', '2021-12-02');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (87, 'SHIPPED', '2022-02-08');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (87, 'OUT FOR DELIVERY', '2022-03-16');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (87, 'DELIVERED', '2022-03-17');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (88, 'SHIPPED', '2021-10-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (88, 'OUT FOR DELIVERY', '2022-02-01');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (88, 'DELIVERED', '2022-03-06');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (89, 'SHIPPED', '2021-04-25');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (89, 'OUT FOR DELIVERY', '2021-09-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (89, 'DELIVERED', '2022-02-20');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (90, 'SHIPPED', '2022-02-25');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (90, 'OUT FOR DELIVERY', '2022-03-04');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (90, 'DELIVERED', '2022-03-30');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (91, 'SHIPPED', '2022-02-07');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (91, 'OUT FOR DELIVERY', '2022-03-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (91, 'DELIVERED', '2022-04-01');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (92, 'SHIPPED', '2022-04-01');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (92, 'OUT FOR DELIVERY', '2022-04-01');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (92, 'DELIVERED', '2022-04-02');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (93, 'SHIPPED', '2021-06-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (93, 'OUT FOR DELIVERY', '2021-06-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (93, 'DELIVERED', '2021-07-24');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (94, 'SHIPPED', '2021-05-26');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (94, 'OUT FOR DELIVERY', '2021-09-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (94, 'DELIVERED', '2021-11-13');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (95, 'SHIPPED', '2021-05-10');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (95, 'OUT FOR DELIVERY', '2021-06-07');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (95, 'DELIVERED', '2021-08-28');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (96, 'SHIPPED', '2022-02-13');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (96, 'OUT FOR DELIVERY', '2022-03-18');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (96, 'DELIVERED', '2022-03-20');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (97, 'SHIPPED', '2022-02-23');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (97, 'OUT FOR DELIVERY', '2022-03-08');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (97, 'DELIVERED', '2022-03-18');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (98, 'SHIPPED', '2022-01-15');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (98, 'OUT FOR DELIVERY', '2022-03-27');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (98, 'DELIVERED', '2022-03-27');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (99, 'SHIPPED', '2021-05-19');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (99, 'OUT FOR DELIVERY', '2022-03-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (99, 'DELIVERED', '2022-03-21');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (100, 'SHIPPED', '2021-10-06');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (100, 'OUT FOR DELIVERY', '2022-03-03');
insert into `LogPengiriman` (`IDBatch`, `Status`, `TimeStamp`) values (100, 'DELIVERED', '2022-03-10');
