insert into `Penyakit` (`IDPenyakit`, `Nama`) values (1, 'Hemophilia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (2, 'A, Hemophilia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (3, 'Hemophilia A');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (4, 'Hepatitis A');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (5, 'A, Hepatitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (6, 'Abdominal Aortic Aneurysm');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (7, 'AAA');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (8, 'Alpha 1 Antitrypsin Deficiency');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (9, 'AAT');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (10, 'AATD');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (11, 'Scar Tissue');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (12, 'Abdominal Adhesions');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (13, 'Heat Cramps');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (14, 'Abdominal Cramps');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (15, 'Hernia Overview');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (16, 'Abdominal Hernia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (17, 'Abdominal Migraines in Children and Adults');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (18, 'Causes, Remedies, Treatment');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (19, 'Abdominal Pain');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (20, 'Abdominoplasty');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (21, 'Tummy Tuck');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (22, 'Ablation Therapy for Arrhythmias');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (23, 'Endometrial Ablation');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (24, 'Ablation, Endometrial');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (25, 'Ablation, Uterus');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (26, 'Uterus Ablation');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (27, 'Heart Rhythm Disorders');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (28, 'Abnormal Heart Rhythms');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (29, 'Liver Blood Tests');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (30, 'Abnormal Liver Enzymes');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (31, 'Vaginal Bleeding');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (32, 'Abnormal Vagnial Bleeding');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (33, 'Miscarriage Causes and Symptoms');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (34, 'Abortion, Spontaneous');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (35, 'Spontaneous Abortion');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (36, 'Cuts, Scrapes and Puncture Wounds');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (37, 'Scrapes and Puncture Wounds Cuts');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (38, 'Abrasion');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (39, 'Abscessed Tooth Guide');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (40, 'Boils');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (41, 'Abscesses, Skin');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (42, 'Skin Abscesses');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (43, 'Amenorrhea');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (44, 'Absence of Menstrual Periods');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (45, 'Urinary Incontinence Products for Men');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (46, 'Absorbent Products Incontinence');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (47, 'Natural Methods of Birth Control');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (48, 'Abstinence Method of Birth Control');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (49, 'Child Abuse Facts');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (50, 'Abuse, Child');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (51, 'Child Abuse');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (52, 'Anabolic Steroid Abuse');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (53, 'Abuse, Steroid');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (54, 'Steroid Abuse');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (55, 'Khat');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (56, 'Abyssinian Tea');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (57, 'ACA or ObamaCare');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (58, 'Affordable Care Act');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (59, 'ACA');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (60, 'Ascites');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (61, 'Accumulation of Fluid in the Abdominal Cavity');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (62, 'Tylenol Liver Damage');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (63, 'Acetaminophen Liver Damage');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (64, 'Achalasia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (65, 'Aches, Pain, Fever');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (66, 'Aches');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (67, 'Achilles Tendon Rupture');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (68, 'Achondroplasia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (69, 'Achondroplastic Dwarfism');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (70, 'GERD');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (71, 'Gastroesophageal Reflux Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (72, 'Acid Reflux');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (73, 'Heartburn and Pregnancy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (74, 'Acid Reflux during Pregnancy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (75, 'GERD in Infants and Children');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (76, 'Acid Reflux in Infants and Children');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (77, 'Acne');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (78, 'Acne Cystic');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (79, 'Rosacea');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (80, 'Acne Rosacea');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (81, 'Scars');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (82, 'Acne Scars');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (83, 'Brain Damage: Symptoms, Causes, Treatment');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (84, 'Acquired Brain Injury');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (85, 'Acquired, Congenital');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (86, 'Congenital Acquired');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (87, 'Bronchiectasis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (88, 'Acquired Bronchiectasis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (89, 'Landau-Kleffner Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (90, 'Acquired Epileptic Aphasia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (91, 'Hydrocephalus');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (92, 'Acquired Hydrocephalus');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (93, 'AIDS');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (94, 'Acquired Immunodeficiency Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (95, 'Skin Tag');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (96, 'Acrochordon');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (97, 'Cushings Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (98, 'ACTH-dependent Hypercortisolism');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (99, 'ACTH-independent Hypercortisolism');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (100, 'Actinic Keratosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (101, 'Acupuncture');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (102, 'Vertigo Overview');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (103, 'Acustic Neuroma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (104, 'Acute and Chronic Bursitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (105, 'Inflammation of the Prostate Gland');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (106, 'Prostatitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (107, 'Acute Bacterial Prostatitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (108, 'Compartment Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (109, 'Acute Compartment Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (110, 'Hepatitis B');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (111, 'Acute Hepatitis B');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (112, 'Porphyria');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (113, 'Acute Intermittent Porphyria');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (114, 'Kidney Failure');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (115, 'Acute Kidney Failure');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (116, 'ARDS');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (117, 'Acute Lung Injury');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (118, 'Leukemia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (119, 'Acute Lymphocytic Leukemia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (120, 'Acute Myeloid Leukemia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (121, 'Pancreatitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (122, 'Acute Pancreatitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (123, 'Acute Porphyria');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (124, 'Acute Respiratory Distress Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (125, 'Valley Fever');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (126, 'Acute Valley Fever');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (127, 'Adenovirus Infection, Ad14');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (128, 'Ad14 Adenovirus Infection');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (129, 'Killer Cold Virus');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (130, 'Ad14');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (131, '13 Tips for Parenting a Teen with ADHD');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (132, 'ADD');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (133, 'ADHD in Children');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (134, 'Drug Abuse');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (135, 'Addiction');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (136, 'Sexual Addiction');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (137, 'Addiction, Sexual');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (138, 'Pernicious Anemia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (139, 'Addison Anemia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (140, 'Addison Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (141, 'Adenoidectomy Surgical Instructions');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (142, 'Adenoids and Tonsils');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (143, 'Adenoids');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (144, 'Gardner Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (145, 'Adenomatous Polyposis Coli');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (146, 'Adenomatous Polyposis of the Colon');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (147, 'Uterine Fibroids');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (148, 'Adenomyosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (149, 'Exercise Stress Test');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (150, 'Adenosine');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (151, 'CAD');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (152, 'Coronary Artery Disease Screening Tests');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (153, 'Adenosine Stress Test For Heart Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (154, 'Adenovirus Infection');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (155, 'Adult ADHD');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (156, 'ADHD in Adults');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (157, 'Parenting a Child With ADHD');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (158, 'ADHD Parenting Tips');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (159, 'Adhesions After Surgery');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (160, 'Frozen Shoulder');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (161, 'Adhesive Capsulitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (162, 'Teenagers');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (163, 'Adolescents');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (164, 'Breastfeeding: Common Breastfeeding Challenges');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (165, 'Adoption and Inducing Lactation');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (166, 'Pheochromocytoma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (167, 'Adrenal Gland Tumor');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (168, 'Adrenal Insufficiency');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (169, 'Adrenal Pheochromocytoma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (170, 'Adult Acne');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (171, 'Psychology');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (172, 'Mental Health');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (173, 'Adult Behavior Disorders');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (174, 'Adult Brain Tumors');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (175, 'Diabetes Mellitus');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (176, 'Adult Onset Diabetes');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (177, 'Stills Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (178, 'Adult Onset Still');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (179, 'Stem Cells');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (180, 'Adult Stem Cells');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (181, 'Adult-Onset Asthma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (182, 'Adults, Abdominal Migraine');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (183, 'Abdominal Migraine Adults');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (184, 'Autism and Communication');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (185, 'Adults, Autism');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (186, 'Autism Adults');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (187, 'Jaundice in Adults');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (188, 'Adults, Jaundice');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (189, 'Jaundice Adults');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (190, 'Advance Medical Directives');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (191, 'Alpha-fetoprotein Blood Test');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (192, 'AFP Blood Test');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (193, 'African Salad');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (194, 'Hirschsprung Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (195, 'Aganglionosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (196, 'Freckles');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (197, 'Age Spots');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (198, 'Macular Degeneration');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (199, 'Age-Related Macular Degeneration');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (200, 'Taste Disorders');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (201, 'Ageusia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (202, 'Prosopagnosia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (203, 'Face Blindness');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (204, 'Agnosia, Facial');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (205, 'Facial Agnosia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (206, 'Agoraphobia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (207, 'Neutropenia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (208, 'Agranulocytosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (209, 'Sea Sickness, Car Sickness');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (210, 'Car Sickness Sea Sickness');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (211, 'Motion Sickness');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (212, 'Air Sick');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (213, 'Alkaptonuria');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (214, 'AKU');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (215, 'ALAD Porphyria');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (216, 'Birthmarks and Other Skin Pigmentation Problems');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (217, 'Albinism');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (218, 'Alcaptonuria');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (219, 'Alcohol Abuse and Alcoholism');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (220, 'Alcohol and Teens');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (221, 'Alcohol Dependence');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (222, 'Alcohol Intoxication in Teens');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (223, 'Alcohol Poisoning in Teens');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (224, 'FAS');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (225, 'Fetal Alcohol Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (226, 'Alcohol, Pregnancy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (227, 'Pregnancy Alcohol');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (228, 'Childbirth Class Options');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (229, 'Alexander Technique for Childbirth');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (230, 'ALK');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (231, 'Keratoplasty Eye Surgery');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (232, 'Childhood Acute Lymphoblastic Leukemia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (233, 'ALL');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (234, 'Asthma Overview');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (235, 'Allergic Asthma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (236, 'Allergic Cascade');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (237, 'Pink Eye');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (238, 'Allergic Conjunctivitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (239, 'Churg-Strauss Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (240, 'Allergic Granulomatosis And Angiitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (241, 'Henoch-Schonlein Purpura');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (242, 'Allergic Purpura');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (243, 'Anaphylaxis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (244, 'Allergic Reaction');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (245, 'Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (246, 'Allergic Rhinitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (247, 'Hay Fever');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (248, 'Allergies');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (249, 'Allergy Shots');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (250, 'Drug Allergies');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (251, 'Allergy to Drugs');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (252, 'Lactose Intolerance');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (253, 'Allergy to Milk');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (254, 'Allergy Treatment Begins At Home');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (255, 'Diaper Rash');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (256, 'Allergy, Diaper');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (257, 'Diaper Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (258, 'Atopic Dermatitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (259, 'Allergy, Eczema');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (260, 'Eczema Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (261, 'Eye Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (262, 'Allergy, Eye');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (263, 'Food Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (264, 'Allergy, Food');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (265, 'Insect Sting Allergies');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (266, 'Allergy, Insect');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (267, 'Insect Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (268, 'Latex Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (269, 'Allergy, Latex');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (270, 'Poison Ivy, Oak, and Sumac');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (271, 'Allergy, Plant Contact');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (272, 'Plant Contact Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (273, 'Rash');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (274, 'Allergy, Rash');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (275, 'Rash Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (276, 'Skin Test For Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (277, 'Allergy, Skin Test');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (278, 'Skin Test Allergy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (279, 'Alopecia Areata');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (280, 'Alpha Thalassemia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (281, 'Alpha-1 Proteinase Inhibitor');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (282, 'Alpha-1 Related Emphysema');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (283, 'Fabrys Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (284, 'Alpha-galactosidase Deficiency');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (285, 'Alport Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (286, 'Amyotrophic Lateral Sclerosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (287, 'ALS');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (288, 'ALT Test');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (289, 'Alternative Therapy for Multiple Sclerosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (290, 'Alternative Treatments for Hot Flashes');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (291, 'Dry Socket Overview');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (292, 'Alveolar Osteitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (293, 'Oral Cancer');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (294, 'Alveolus Cancer');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (295, 'Alzheimers Disease Causes, Stages, and Symptoms');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (296, 'Financial Planning in Alzheimers Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (297, 'Alzheimers Disease Financial Planning');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (298, 'Alzheimers Disease Patient Caregiver Guide');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (299, 'Antimitochondrial Antibodies');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (300, 'AMA');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (301, 'Amblyopia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (302, 'Chagas Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (303, 'American Trypanosomiasis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (304, 'Homocysteine');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (305, 'Amino Acid, Homocysteine');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (306, 'Homocysteine Amino Acid');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (307, 'AML');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (308, 'Ammonia Dermatitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (309, 'Ammonia Rash');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (310, 'Amniocentesis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (311, 'Amniotic Fluid');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (312, 'Amyloidosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (313, 'Antinuclear Antibody');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (314, 'ANA');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (315, 'Anal Cancer');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (316, 'Anal Fissure');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (317, 'Anal Itching');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (318, 'Anal Tear');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (319, 'Urinalysis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (320, 'Analysis of Urine');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (321, 'Anaphylactoid Purpura');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (322, 'Anaplastic Astrocytomas');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (323, 'Thyroid Cancer');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (324, 'Anaplastic Carcinoma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (325, 'Anemia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (326, 'Anencephaly');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (327, 'Anencephalia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (328, 'Anencephalus');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (329, 'Spina Bifida and Anencephaly');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (330, 'Malignant Hyperthermia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (331, 'Anesthesia Related Hyperthermia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (332, 'Brain Aneurysm');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (333, 'Aneurysm');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (334, 'Aneurysm of Aorta');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (335, 'Aneurysm of Belly');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (336, 'Angelman Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (337, 'Vasculitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (338, 'Angiitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (339, 'Angina Symptoms');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (340, 'Klippel-Trenaunay-Weber Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (341, 'Angio-Osteohypertrophy Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (342, 'Hives');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (343, 'Angioedema');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (344, 'Coronary Angiogram');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (345, 'Angiogram Of Heart');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (346, 'Coronary Angioplasty');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (347, 'Angioplasty');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (348, 'Glaucoma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (349, 'Angle Closure Glaucoma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (350, 'Ankle Dislocation');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (351, 'Dislocated Ankle');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (352, 'Ankle Pain and Tendinitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (353, 'Swollen Ankles and Swollen Feet');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (354, 'Ankle, Swollen');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (355, 'Swollen Ankle');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (356, 'Ankylosing Spondylitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (357, 'Heart Valve Disease Treatment');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (358, 'Annulus Support');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (359, 'Anorexia Nervosa');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (360, 'Anovulation');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (361, 'Encephalopathy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (362, 'Anoxia Encephalopathy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (363, 'Knee Bursitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (364, 'Anserine Bursitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (365, 'Spondylolisthesis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (366, 'Anterolisthesis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (367, 'Anthrax');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (368, 'Citrulline Antibody');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (369, 'Anti-CCP');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (370, 'Anti-citrulline Antibody');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (371, 'Anti-cyclic Citrullinated Peptide Antibody');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (372, 'Antiemetics');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (373, 'Anti-nausea');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (374, 'Fundoplication');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (375, 'Anti-Reflux Surgery');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (376, 'Anti-vomiting');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (377, 'Antibiotic Resistance');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (378, 'Clostridium Difficile Colitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (379, 'Antibiotic-Caused Colitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (380, 'XDR TB');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (381, 'Extensively Drug-Resistant Tuberculosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (382, 'Antibiotic-Resistant Tuberculosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (383, 'Antibiotic-Resistant Tuberculosis XDR-TB');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (384, 'Antiphospholipid Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (385, 'Anticardiolipin Antibody');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (386, 'Thyroid Peroxidase Test');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (387, 'Antimicrosomal Antibody Test');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (388, 'Antisocial Personality Disorder');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (389, 'Antithyroid Microsomal Antibody Test');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (390, 'Antitrypsin');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (391, 'Facial Nerve Problems');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (392, 'Antonis Palsy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (393, 'Antro-duodenal Motility Study');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (394, 'Anxiety');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (395, 'Anxiety Disorder');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (396, 'Separation Anxiety');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (397, 'Anxiety, Separation');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (398, 'Aortic Dissection');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (399, 'Aortic Heart Valve Replacement');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (400, 'Aortic Stenosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (401, 'APC');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (402, 'Auditory Processing Disorder in Children');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (403, 'APD');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (404, 'Apgar Score');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (405, 'Aphasia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (406, 'Aphasia with Convulsive Disorder');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (407, 'Canker Sores');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (408, 'Aphthous Ulcers');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (409, 'Sleep Apnea');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (410, 'Apnea, Sleep');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (411, 'Sever Condition');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (412, 'Apophysitis Calcaneus');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (413, 'Appendectomy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (414, 'Appendicitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (415, 'Appendix');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (416, 'Aprosencephaly');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (417, 'Arachnoiditis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (418, 'Breast Anatomy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (419, 'Areola');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (420, 'Muscle Cramps');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (421, 'Arm Cramp');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (422, 'Sudden Cardiac Death');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (423, 'Arrest, Cardiac');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (424, 'Cardiac Arrest');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (425, 'Irregular Heartbeat');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (426, 'Arrhythmia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (427, 'Arrhythmia Treatment');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (428, 'Arsenic Poisoning');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (429, 'Infertility');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (430, 'ART');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (431, 'Coronary Artery Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (432, 'Heart Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (433, 'Arteriosclerosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (434, 'Arteriovenous Malformation');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (435, 'Arteritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (436, 'Carotid Artery Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (437, 'Artery, Carotid Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (438, 'Carotid Disease Artery');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (439, 'Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (440, 'Arthralgia');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (441, 'Juvenile Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (442, 'Arthritis In Children');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (443, 'Arthritis Physical and Occupational Therapy');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (444, 'Arthritis, Ankylosing Spondylitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (445, 'Ankylosing Spondylitis Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (446, 'Osteoarthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (447, 'Arthritis, Degenerative');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (448, 'Degenerative Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (449, 'Gouty Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (450, 'Gout');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (451, 'Arthritis, Gout');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (452, 'Gout Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (453, 'Septic Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (454, 'Arthritis, Infectious');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (455, 'Infectious Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (456, 'Arthritis, Juvenile');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (457, 'Lyme Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (458, 'Arthritis, Lyme');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (459, 'Lyme Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (460, 'Mixed Connective Tissue Disease');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (461, 'Arthritis, MCTD');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (462, 'MCTD Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (463, 'Plant Thorn Synovitis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (464, 'Arthritis, Plant Thorn');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (465, 'Plant Thorn Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (466, 'Pseudogout');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (467, 'Arthritis, Pseudogout');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (468, 'Pseudogout Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (469, 'Psoriatic Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (470, 'Arthritis, Psoriatic');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (471, 'Quackery Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (472, 'Arthritis, Quackery');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (473, 'Reactive Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (474, 'Arthritis, Reactive');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (475, 'Arthritis, Reiters');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (476, 'Reiters Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (477, 'Rheumatoid Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (478, 'Arthritis, Rheumatoid');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (479, 'Sarcoidosis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (480, 'Arthritis, Sarcoid');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (481, 'Sarcoid Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (482, 'Scleroderma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (483, 'Arthritis, Scleroderma');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (484, 'Scleroderma Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (485, 'Sjogrens Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (486, 'Arthritis, Sjogren Syndrome');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (487, 'Sjogren Syndrome Arthritis');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (488, 'Systemic Lupus');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (489, 'Arthritis, SLE');
insert into `Penyakit` (`IDPenyakit`, `Nama`) values (490, 'SLE Arthritis');
