insert into `Provinsi` (`IDProvinsi`, `Nama`) values (1, 'Aceh');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (2, 'Bali');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (3, 'Banten');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (4, 'Bengkulu');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (5, 'DKI Yogyakarta');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (6, 'DKI Jakarta');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (7, 'Gorontalo');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (8, 'Jambi');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (9, 'Jawa Barat');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (10, 'Jawa Tengah');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (11, 'Jawa Timur');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (12, 'Kalimantan Barat');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (13, 'Kalimantan Selatan');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (14, 'Kalimantan Tengah');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (15, 'Kalimantan Timur');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (16, 'Kalimantan Utara');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (17, 'Kepulauan Bangka Belitung');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (18, 'Kepulauan Riau');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (19, 'Lampung');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (20, 'Maluku');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (21, 'Maluku Utara');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (22, 'Nusa Tenggara Barat');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (23, 'Nusa Tenggara Timur');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (24, 'Papua');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (25, 'Papua Barat');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (26, 'Riau');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (27, 'Sulawesi Barat');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (28, 'Sulawesi Selatan');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (29, 'Sulawesi Tengah');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (30, 'Sulawesi Tenggara');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (31, 'Sulawesi Utara');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (32, 'Sumatera Barat');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (33, 'Sumatera Selatan');
insert into `Provinsi` (`IDProvinsi`, `Nama`) values (34, 'Sumatera Utara');
