insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (1, 'BioNTech', 'Costa Rica');
insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (2, 'CoronaVac', 'Zimbabwe');
insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (3, 'Moderna', 'Brunei Darussalam');
insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (4, 'Novavax', 'Antigua and Barbuda');
insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (5, 'Oxford', 'India');
insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (6, 'Sinopharm', 'Holy See (Vatican City State)');
insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (7, 'Sputnik V', 'Thailand');
insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (8, 'CanSino', 'Nauru');
insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (9, 'Janssen', 'Uruguay');
insert into `Vaksin` (`IDVaksin`, `Nama`, `Produsen`) values (10, 'RBD - Dimer', 'Vietnam');
